spring:
  datasource:
    url: ${DB_URL:${JDBC_DATABASE_URL:}}
    username: ${DB_USERNAME:${JDBC_DATABASE_USERNAME:}}
    password: ${DB_PASSWORD:${JDBC_DATABASE_PASSWORD:}}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: ${FLYWAY_ENABLED:true}

server:
  port: ${PORT:8080}

friendlywager:
  security:
    jwt:
      issuer: ${JWT_ISSUER:friendly-wager}
      secret: ${JWT_SECRET}
      expiration-minutes: ${JWT_EXP_MINUTES:120}

# Optional CORS config
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}

