name: Deploy to Elastic Beanstalk

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
  EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR
        run: |
          ./mvnw -q -DskipTests package

      - name: Prepare artifact
        run: |
          mkdir -p bundle
          cp target/friendly-wager-0.0.1-SNAPSHOT.jar bundle/app.jar
          cp Procfile bundle/Procfile
          mkdir -p bundle/.ebextensions bundle/.platform/hooks/prebuild
          cp -r .ebextensions/* bundle/.ebextensions/ || true
          cp -r .platform/hooks/prebuild/* bundle/.platform/hooks/prebuild/ || true
          cd bundle && zip -r ../deploy.zip . && cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3 and create EB application version
        run: |
          S3_BUCKET=${{ secrets.EB_S3_BUCKET }}
          VERSION_LABEL=fw-${{ github.run_id }}-${{ github.run_number }}
          aws s3 cp deploy.zip s3://$S3_BUCKET/$VERSION_LABEL.zip
          aws elasticbeanstalk create-application-version \
            --application-name "$EB_APPLICATION_NAME" \
            --version-label "$VERSION_LABEL" \
            --source-bundle S3Bucket=$S3_BUCKET,S3Key=$VERSION_LABEL.zip
          aws elasticbeanstalk update-environment \
            --environment-name "$EB_ENVIRONMENT_NAME" \
            --version-label "$VERSION_LABEL"

